// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdUsC7D8huhcPVVmagiBsnHgp7bcOi-fo',
    appId: '1:541551018302:web:217924b2d99797fd4b2c6f',
    messagingSenderId: '541551018302',
    projectId: 'shopmix-8019f',
    authDomain: 'shopmix-8019f.firebaseapp.com',
    databaseURL: 'https://shopmix-8019f-default-rtdb.firebaseio.com',
    storageBucket: 'shopmix-8019f.appspot.com',
    measurementId: 'G-75D38MT0Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9uKGO3LxqChzBbhadlZ99xmhVNgRL18',
    appId: '1:541551018302:android:f787f3a90f9bef674b2c6f',
    messagingSenderId: '541551018302',
    projectId: 'shopmix-8019f',
    databaseURL: 'https://shopmix-8019f-default-rtdb.firebaseio.com',
    storageBucket: 'shopmix-8019f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bcdZK6UJlXxc8tGq5rp-4GKhF_YXRcU',
    appId: '1:541551018302:ios:c110f5f7ba22edfb4b2c6f',
    messagingSenderId: '541551018302',
    projectId: 'shopmix-8019f',
    databaseURL: 'https://shopmix-8019f-default-rtdb.firebaseio.com',
    storageBucket: 'shopmix-8019f.appspot.com',
    iosClientId: '541551018302-eq1e3gfaark51malekrlvr1fqjagfcv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopmixdelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bcdZK6UJlXxc8tGq5rp-4GKhF_YXRcU',
    appId: '1:541551018302:ios:c110f5f7ba22edfb4b2c6f',
    messagingSenderId: '541551018302',
    projectId: 'shopmix-8019f',
    databaseURL: 'https://shopmix-8019f-default-rtdb.firebaseio.com',
    storageBucket: 'shopmix-8019f.appspot.com',
    iosClientId: '541551018302-eq1e3gfaark51malekrlvr1fqjagfcv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopmixdelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdUsC7D8huhcPVVmagiBsnHgp7bcOi-fo',
    appId: '1:541551018302:web:97b882191788d5814b2c6f',
    messagingSenderId: '541551018302',
    projectId: 'shopmix-8019f',
    authDomain: 'shopmix-8019f.firebaseapp.com',
    databaseURL: 'https://shopmix-8019f-default-rtdb.firebaseio.com',
    storageBucket: 'shopmix-8019f.appspot.com',
    measurementId: 'G-V0NZ12Y97G',
  );
}
